### ISSUE TITLE
Maven 

### ISSUE THREAD

**Issue by suncunhu** [pospospos2007/albert#1]
Java项目Maven 是必须的吧.。。。。。

**Comment by pospospos2007** [comment]
maven的话的确在我考虑中，但是目前由于我这个应用中的一些包是经过修改后自己打包的，比如dubbo包，在网上你是一般找不到我这个版本的包的，你可以看一下。所有的包我全都给你上传了，这样就保证不会down下来发现为什么有些包down不了
